# Generated by Django 4.1.6 on 2023-02-05 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myApp", "0002_profile_acadmicyear_profile_branch_profile_github_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="birth_date",
        ),
        migrations.AddField(
            model_name="profile",
            name="view_count",
            field=models.IntegerField(default=0),
        ),
    ]
