# Generated by Django 4.1.6 on 2023-02-05 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myApp", "0003_remove_profile_birth_date_profile_view_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="profileimg",
            field=models.ImageField(
                default="default-user.png", upload_to="profile_images"
            ),
        ),
    ]
