# Generated by Django 4.1.6 on 2023-03-15 19:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("myApp", "0004_profile_profileimg"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="profileimg",
            field=models.ImageField(
                default="profile_images/default-user.png", upload_to="profile_images"
            ),
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("tech_stack", models.CharField(max_length=200)),
                ("date_started", models.DateField()),
                ("github_link", models.URLField(blank=True)),
                ("website_link", models.URLField(blank=True)),
                ("image_1", models.ImageField(blank=True, upload_to="project_images")),
                ("image_2", models.ImageField(blank=True, upload_to="project_images")),
                ("image_3", models.ImageField(blank=True, upload_to="project_images")),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
