# Generated by Django 4.1.6 on 2023-03-16 10:39

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("myApp", "0005_alter_profile_profileimg_post"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="post_thumbnail",
            field=models.ImageField(blank=True, upload_to="project_images"),
        ),
        migrations.AlterField(
            model_name="post",
            name="date_started",
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name="post",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, primary_key=True, serialize=False
            ),
        ),
    ]
