# Generated by Django 4.1.6 on 2023-03-16 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("myApp", "0006_post_post_thumbnail_alter_post_date_started_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="user_profile",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="myApp.profile",
            ),
        ),
    ]
