# Generated by Django 4.1.6 on 2023-03-21 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myApp", "0007_post_user_profile"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="other",
            new_name="twitter",
        ),
    ]
