# Generated by Django 4.1.6 on 2023-04-02 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myApp", "0010_profile_profession"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="mobilenumber",
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
