# Generated by Django 4.1.6 on 2023-04-03 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myApp", "0011_profile_mobilenumber"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="firstsetting",
            field=models.BooleanField(default=False),
        ),
    ]
