# Generated by Django 4.1.6 on 2023-04-17 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myApp", "0016_post_youtube_link"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="youtube_link",
        ),
    ]
