# Generated by Django 4.1.6 on 2023-04-18 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myApp", "0021_profile_total_post_views"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="total_views",
            new_name="profile_views",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="view_count",
        ),
    ]
